language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
cache: pip
notifications:
  email:
    - thierryschellenbach@gmail.com
    - tbarbugli@gmail.com

install:
  - pip install -r dev_requirements.txt
script:
  - py.test stream/tests.py -slv --cov stream --cov-report term-missing
after_script:
  # ensure we validate against pep standards
  - "pep8 --exclude=migrations --ignore=E501,E225,W293 stream"
after_success:
   - coveralls
