language: python
sudo: false
python:
  - '2.7.8'
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  # These are allowed to fail
  - '3.5-dev' # 3.5 development branch
  - '3.6-dev' # 3.6 development branch
  - 'nightly' # currently points to 3.7-dev
  - 'pypy'
  - 'pypy3'

matrix:
  fast_finish: true
  allow_failures:
    - python: '3.5-dev' # 3.5 development branch
    - python: '3.6-dev' # 3.6 development branch
    - python: 'nightly'
    - python: 'pypy'
    - python: 'pypy3'

cache: pip
notifications:
  email:
    - thierryschellenbach@gmail.com
    - tbarbugli@gmail.com

install:
  - pip install -r dev_requirements.txt
script:
  - py.test stream/tests.py -lv --cov stream --cov-report term-missing
after_script:
  # ensure we validate against pep standards
  - "pep8 --exclude=migrations --ignore=E501,E225,W293 stream"
after_success:
   - coveralls
